name: Archive feature branch

on:
  workflow_call:
    inputs:
      git-branch:
        required: true
        type: string
  
permissions:
  contents: write

jobs:
  archive-feature-branch:
    if: startsWith(inputs.git-branch, 'feature/') && ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git-branch }}

      - name: Create archive ref
        run: |
          git update-ref "refs/archive/${{ inputs.git-branch }}" "${{ inputs.git-branch }}"
          git push origin refs/archive/*:refs/archive/*

      - name: Delete feature branch
        run: git push -d origin "${{ inputs.git-branch }}"