name: Archive feature branch (after merge)

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  
jobs:
  call-archive-workflow:
    uses: ./.github/workflows/archive-feature-branch.yml
    with:
      git-branch: ${{ github.head_ref }}