name: Archive feature branch (manual)

on:
  workflow_dispatch:

jobs:
  call-archive-workflow:
    uses: ./.github/workflows/archive-feature-branch.yml
    with:
      git-branch: ${{ github.ref_name }}