name: Archive feature branch (manual2)

on:
  push: 

permissions:
  contents: write

jobs:
  call-archive-workflow:
    uses: markusroessler/Github.Actions.Playground/.github/workflows/archive-feature-branch.yml@develop
    with:
      git-branch: ${{ github.ref_name }}
      