name: Release Build

on: 
  workflow_dispatch:
    inputs:
        release-version:
          description: 'Version to release'
          required: true
          default: ''

permissions:
  contents: write
  checks: write
  issues: read
  packages: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core SDK 7.0.x
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Init nuget source
      run: dotnet nuget add source --username markusroessler --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/markusroessler/index.json"

    - name: Init nuget cache
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build
      id: build
      run: |
        dotnet build -p:Configuration=Release -p:ErrorLog="compiler-diagnostics.sarif%2Cversion=2.1"

    - name: Test
      if: always()
      run: dotnet test -p:Configuration=Release --logger:html --logger:"trx;LogFileName=TestResults/TestResults.trx" --no-build

    - name: Pack nuget package
      run: dotnet pack GithubSarifCollector.Csl -p:Configuration=Release -p:Version=${{ inputs.release-version }}

    - name: Push nuget package
      run: dotnet nuget push GithubSarifCollector.Csl/bin/Release/net7.0/GithubSarifCollector.Csl-${{ inputs.release-version }}.nuget --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"

    - name: Publish Github Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: GithubSarifCollector.Csl/bin/Release/net7.0/GithubSarifCollector.Csl-${{ inputs.release-version }}.nuget
        name: ${{ inputs.release-version }}
        tag: ${{ steps.get-version.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: GithubSarifCollector-ci-quick-test-report
        path: '**/TestResults/*.html'

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: "**/TestResults/TestResults.trx"
        check_name: "check: test results"
        check_run_annotations_branch: "*"

    # - name: Collect Build Results
    #   id: collect-build-results
    #   if: always()
    #   run: dotnet run --project Build.CollectResults.Csl

    # - name: Publish Build Results
    #   uses: LouisBrunner/checks-action@v1.6.1
    #   if: always()
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     name: "check: build results"
    #     conclusion: ${{ steps.collect-build-results.outputs.checks-action-conclusion }}
    #     output: ${{ steps.collect-build-results.outputs.checks-action-output }}
    #     annotations: ${{ steps.collect-build-results.outputs.checks-action-annotations }}
