name: Release Build

on: 
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version to release'
        required: true
        default: ''

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release ${{ inputs.release-version }}
    runs-on: ubuntu-latest

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core SDK 7.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        cache: true
        cache-dependency-path: "*/packages.lock.json"
     
    - name: Remove setup-dotnet problem matcher
      run: echo "::remove-matcher owner=csc::"

    - name: Init nuget source
      run: dotnet nuget add source --username markusroessler --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/markusroessler/index.json"

    - name: Git Config
      run: |
        git config --global user.name 'Github Actions'
        git config --global user.email 'github.actions@users.noreply.github.com'
    
    - name: Create Tag
      run: |
        git tag -a "release/${{ inputs.release-version }}" -m "Release ${{ inputs.release-version }} [skip ci]"
        git push origin "refs/tags/release/${{ inputs.release-version }}"

    - name: Restore
      run: | 
        dotnet restore --locked-mode -p:Configuration=Release
        dotnet tool restore
        
    - name: Build
      id: build
      run: dotnet build --no-restore -p:Configuration=Release -p:ErrorLog="compiler-diagnostics.sarif%2Cversion=2.1"

    - name: Test
      if: always()
      run: dotnet test -p:Configuration=Release --logger:html --logger:"trx;LogFileName=TestResults/TestResults.trx" --no-build

    - name: Pack nuget package
      run: dotnet pack GithubDotnetResultsExporter.Csl -p:Configuration=Release -p:Version=${{ inputs.release-version }}

    - name: Push nuget package
      run: dotnet nuget push GithubDotnetResultsExporter.Csl/bin/Release/GithubDotnetResultsExporter.${{ inputs.release-version }}.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"

    - name: Install package as tool
      if: always()
      run: dotnet tool install --global GithubDotnetResultsExporter --version ${{ inputs.release-version }}

    - name: Collect Build Results
      id: collect-build-results
      if: always()
      run: export-dotnet-results-for-github --export-step-summary true --github-server-url ${{ github.server_url }} --github-repo ${{ github.repository }} --github-ref-name ${{ github.ref_name }} --culture "de-DE"

    - name: Publish Github Release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ inputs.release-version }}
        tag: "release/${{ inputs.release-version }}"
        artifacts: GithubDotnetResultsExporter.Csl/bin/Release/GithubDotnetResultsExporter.${{ inputs.release-version }}.nupkg
        generateReleaseNotes: true
        draft: false
        prerelease: ${{ github.ref_name != 'main' }}
        makeLatest: ${{ github.ref_name == 'main' }}

    - name: Upload Test Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: GithubDotnetResultsExporter-release-test-report
        path: '**/TestResults/*.html'
